# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1

workflows:
  build-and-deploy:
    jobs:
      - install-dependencies:
          filters:
            branches:
              only:
                - main
      - build:
          requires:
            - install-dependencies
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main

jobs:
  install-dependencies:
    working_directory: ~/project
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages
      - persist_to_workspace:
          root: workspace
          paths:
            - node_modules

  build:
    working_directory: ~/project
    executor:
      name: node/default
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - run:
          name: Build stuff
          command: npm run build
      - persist_to_workspace:
          root: workspace
          paths:
            - dist

  deploy:
    working_directory: ~/project
    executor:
      name: node/default
    steps:
      - checkout
      - attach_workspace:
          at: workspace
      - run:
          name: Deploy
          command: scp -r / "$SSH_USER@$SSH_HOST:$SSH_DEPLOY_PATH"
