# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1

workflows:
  build-and-deploy:
    jobs:
      - install-dependencies:
          filters:
            branches:
              only:
                - main
      - build:
          requires:
            - install-dependencies
          filters:
            branches:
              only:
                - main
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - main

jobs:
  install-dependencies:
    working_directory: ~/project
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Installing dependencies
          command: npm install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
              - node_modules

  build:
    working_directory: ~/project
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Building dist
          command: npm run build
      - persist_to_workspace:
          root: ~/project
          paths:
            - dist

  deploy:
    working_directory: ~/project
    executor:
      name: node/default
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Log
          command: ls
      - run:
          name: Add to known hosts
          command: sudo ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "$SSH_FINGERPRINT"
      - run:
          name: Deploy
          command: scp -r ./ "$SSH_USER@$SSH_HOST:$SSH_DEPLOY_PATH"
